### ISSUE TITLE
Exception in persistSync

### ISSUE THREAD

**Issue by omarsahl** [novoda/download-manager#444] opened 2018-10-15 00:32 UTC
I get this message when trying to download a batch with two files
`[[pool-2-thread-1][(DownloadsFilePersistence.java:41).persistSync] , failure to persist sync file video with status QUEUED]`

After debugging I found out that it's a SQLite exception
```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
#################################################################
Error Code : 787 (SQLITE_CONSTRAINT_FOEIGNKEY)
Caused By : Abort due to constraint violation.
	(FOREIGN KEY constraint failed (code 787))
#################################################################
```
Any help would be appreciated. Thanks.

**Comment by MechaRyRy** [comment] 2018-10-15 08:48
Hi @omar753sahl I believe you will only see this the first time it attempts to persist into the DB and this is because of some technical debt on our part. If memory serves this crops up because we are attempting to add a file before we have added a batch which is why the foreign key fails. 

Either way, this shouldn't cause any issues. If you are having problems please get back in touch. You should be able to use [Stetho](https://medium.com/quick-mobile/stetho-a-debugging-bridge-for-android-applications-eacc139dfda7) to check the database.

**Comment by omarsahl** [comment] 2018-10-16 03:49
Thanks for the clarification @Mecharyry 
I thought this was an issue as the batch wasn't downloaded. I didn't get any notification or anything.

**Comment by MechaRyRy** [comment] 2018-10-16 07:15
This might be a different issue then. Have you been able to reproduce using the `demo` of the library? I'd suggest you start there if you are having any sort of issues.

**Comment by omarsahl** [comment] 2018-10-16 09:28
Actually, I haven't used the demo at all. The library isn't that hard to use.
I have a singleton instance of `DownloadManager` injected through dagger2 like this
```
    @Provides
    @Singleton
    fun provideDownloader(context: Context): DownloadManager {
        val handler = Handler(Looper.getMainLooper())
        return DownloadManagerBuilder.newInstance(context, handler, R.drawable.ic_download_main)
                .withAllowedConnectionType(ConnectionType.ALL)
                .withLogHandle(DownloaderLogHandler())
                .withNotificationChannel("${context.packageName}.$CHANNEL_ID_POSTFIX",
                        CHANNEL_NAME,
                        NotificationManagerCompat.IMPORTANCE_DEFAULT)
                .build()
    }
```
And then I use it to download some files in a batch
```kotlin
manager.download(createBatchFromDownloadOption(downloadOption))
manager.addDownloadBatchCallback {
       Timber.d("status=${it.status().toRawValue()}, ${it.percentageDownloaded()}%")
}
```
The batch is created like this:
```
Batch.with(root, DownloadBatchIdCreator.createSanitizedFrom(id), cleanName)
                        .downloadFrom(url).saveTo("tbm", id)
                        .withIdentifier(DownloadFileIdCreator.createFrom("video")).apply()
                        .build()
```

**Comment by omarsahl** [comment] 2018-10-16 09:28
Am I missing something?

**Comment by MechaRyRy** [comment] 2018-10-16 09:37
It looks correct to me @omar753sahl, the only thing that looks a bit strange is the use of the same `id` for the batch and the file name but I can't see that being a problem. I'd suggest trying it out on the demo and see if you still have problems, or failing that perhaps linking some more verbose logs? Using the download manager log handle, that you already have added 😄

**Comment by omarsahl** [comment] 2018-10-16 10:37
So after tinkering around for a while, I found that for some reason the `LiteDownloadService` wasn't included in the merged Manifest.
So after explicitly adding It to the Manifest, It works!
Thanks for your help @Mecharyry

**Comment by MechaRyRy** [comment] 2018-10-16 10:58
How strange! Thanks for letting me know @omar753sahl, I'm going to close this issue now.

**Closed as completed by MechaRyRy** 2018-10-16 10:58 UTC
Labels: question
