### ISSUE TITLE
When `Content-Length` is missing from Response, retry continues indefinitely

### ISSUE THREAD

**Issue by mspmax** [novoda/download-manager#485] opened 2019-03-11 03:20 UTC
Hi Guys, 

I came across an issue during error handling and not sure whether it's a known one or i'm missing something here. When `Content-Length` is missing in the response header the system goes to an infinite loop(retries indefinitely) any clue on this? 

Thanks in advance!

**Comment by danybony** [comment] 2019-03-11 09:10
Hi @mspmax, thanks for notify on the issue.
Do you have an example URL we can try to reproduce it?

**Comment by mspmax** [comment] 2019-03-12 05:48
Hi @danybony, thanks for the quick reply. Well basically our QA guys have tested with a dummy request URL which does not have `Content-Length` eg: google.com I know it sounds like an edge case but not sure why it does not fallback gracefully. Let me know your thoughts on this :). Cheers!

**Comment by MechaRyRy** [comment] 2019-03-13 09:16
Hi @mspmax, this particular issue would relate to #483. From what I can tell the likely thing that is happening here is that: 

- `FileSizeRequester` performs a header request for the size, looking for `Content-Length` which is not present and therefor it will
- perform a body request, this body request will then be 0
- it will then try to download the file which will fail, this failure will be transformed to a network error which then forces a retry

Would you be able to provide any logs? This would help to confirm the above suspicion. This would likely be fixed with the changes we are making in #483 because we are giving more control to the client applications on network error.

**Comment by mspmax** [comment] 2019-03-13 23:23
Hi @Mecharyry, you're correct and this is the exact issue happening. I did debug. Anyway, I did a workaround as below, a sanity step to validate the URL and then terminate the stream if there's no `Content-Length` before triggering the download manager.

``` java
private Completable validateDownloadUrl(@NonNull String url) {
        return Completable.create(emitter -> {
            Request.Builder requestBuilder = new Request.Builder().url(url);
            requestBuilder = requestBuilder.head();

            requestBuilder.addHeader("Accept-Encoding", "identity");

            Call call = axisHttpClient.getOkHttpClient().build().newCall(requestBuilder.build());

            Response response = call.execute();

            if (response.isSuccessful()) {
                // check for content-length header value
                String value = response.header("Content-Length", "");
                if (StringUtils.isNull(value)) {
                    emitter.onError(new DownloadIntegrityException("URL is not valid, can not continue download"));
                } else {
                    emitter.onComplete();
                }
            } else {
                emitter.onError(new DownloadIntegrityException("HEAD request not successful"));
            }
        }).compose(RxUtils.Completables.setSchedulers());
}
```

**Comment by MechaRyRy** [comment] 2019-03-14 08:12
@mspmax that workaround makes the most sense until we can build something into the `download-manager` to handle this. If you don't mind I'll close this ticket and reference it in the other as they are related.

**Closed as completed** 2019-03-14 08:13 UTC
Labels: duplicate
